# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 07:57
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='profile'),
        ),
    ]
