# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 13:58
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
                name='Post',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('text', models.TextField(blank=True)),
                    ('image', models.ImageField(blank=True, upload_to='')),
                    ('category', models.CharField(blank=True,
                                                  choices=[('Video', 'Video'), ('Picture', 'Picture'), ('Jape', 'Jape'),
                                                           ('Others', 'Others')], max_length=20, null=True,
                                                  verbose_name='Belong to')),
                    ('pub_date', models.DateTimeField(auto_now_add=True)),
                    ('comment_num', models.IntegerField(default=0)),
                    ('praise_num', models.IntegerField(default=0)),
                    ('tread_num', models.IntegerField(default=0)),
                ],
        ),
        migrations.AlterField(
                model_name='newuser',
                name='username',
                field=models.CharField(error_messages={'unique': 'A user with that username already exists.'},
                                       help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                       max_length=150, unique=True,
                                       validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                                       verbose_name='username'),
        ),
    ]
