# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='article',
                name='author',
        ),
        migrations.RemoveField(
                model_name='article',
                name='column',
        ),
        migrations.RemoveField(
                model_name='article',
                name='user',
        ),
        migrations.AlterModelOptions(
                name='note',
                options={'ordering': ['pub_date'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.DeleteModel(
                name='Article',
        ),
        migrations.DeleteModel(
                name='Author',
        ),
        migrations.DeleteModel(
                name='Column',
        ),
    ]
