# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('focus', '0002_auto_20161211_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
                name='note',
                options={'ordering': ['id'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.AddField(
                model_name='praise',
                name='praise_date',
                field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                preserve_default=False,
        ),
        migrations.AddField(
                model_name='share',
                name='share_date',
                field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                preserve_default=False,
        ),
        migrations.AddField(
                model_name='tread',
                name='tread_date',
                field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                preserve_default=False,
        ),
        migrations.AlterField(
                model_name='comment',
                name='user',
                field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                        to=settings.AUTH_USER_MODEL, verbose_name='who comment'),
        ),
        migrations.AlterField(
                model_name='note',
                name='user',
                field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                        to=settings.AUTH_USER_MODEL, verbose_name='who public'),
        ),
        migrations.AlterField(
                model_name='praise',
                name='user',
                field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                        to=settings.AUTH_USER_MODEL, verbose_name='who praise'),
        ),
        migrations.AlterField(
                model_name='share',
                name='user',
                field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                        to=settings.AUTH_USER_MODEL, verbose_name='who share'),
        ),
        migrations.AlterField(
                model_name='tread',
                name='user',
                field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                        to=settings.AUTH_USER_MODEL, verbose_name='who tread'),
        ),
    ]
