# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('focus', '0002_auto_20161209_2158'),
    ]

    operations = [
        migrations.CreateModel(
                name='Note',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('text', models.TextField(blank=True)),
                    ('image', models.ImageField(blank=True, upload_to='')),
                    ('category', models.CharField(blank=True,
                                                  choices=[('Video', 'Video'), ('Picture', 'Picture'), ('Jape', 'Jape'),
                                                           ('Others', 'Others')], max_length=20, null=True,
                                                  verbose_name='Belong to')),
                    ('pub_date', models.DateTimeField(auto_now_add=True)),
                    ('comment_num', models.IntegerField(default=0)),
                    ('praise_num', models.IntegerField(default=0)),
                    ('tread_num', models.IntegerField(default=0)),
                ],
                options={
                    'verbose_name_plural': 'notes',
                    'verbose_name': 'note',
                },
        ),
        migrations.CreateModel(
                name='Praise',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ],
        ),
        migrations.CreateModel(
                name='Share',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('text', models.CharField(blank=True, max_length=200, null=True)),
                    ('to', models.CharField(max_length=256)),
                    ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focus.Note')),
                ],
        ),
        migrations.CreateModel(
                name='Tread',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ],
        ),
        migrations.RemoveField(
                model_name='poll',
                name='article',
        ),
        migrations.RemoveField(
                model_name='poll',
                name='comment',
        ),
        migrations.RemoveField(
                model_name='poll',
                name='user',
        ),
        migrations.DeleteModel(
                name='Post',
        ),
        migrations.RenameField(
                model_name='comment',
                old_name='poll_num',
                new_name='praise_num',
        ),
        migrations.RenameField(
                model_name='comment',
                old_name='content',
                new_name='text',
        ),
        migrations.RemoveField(
                model_name='article',
                name='poll_num',
        ),
        migrations.RemoveField(
                model_name='comment',
                name='article',
        ),
        migrations.RemoveField(
                model_name='comment',
                name='user',
        ),
        migrations.AddField(
                model_name='comment',
                name='tread_num',
                field=models.IntegerField(default=0),
        ),
        migrations.AddField(
                model_name='newuser',
                name='sex',
                field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=10),
        ),
        migrations.AlterField(
                model_name='newuser',
                name='profile',
                field=models.CharField(default='', max_length=255, verbose_name='profile'),
        ),
        migrations.DeleteModel(
                name='Poll',
        ),
        migrations.AddField(
                model_name='tread',
                name='comment',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        to='focus.Comment'),
        ),
        migrations.AddField(
                model_name='tread',
                name='note',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        to='focus.Note'),
        ),
        migrations.AddField(
                model_name='praise',
                name='comment',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        to='focus.Comment'),
        ),
        migrations.AddField(
                model_name='praise',
                name='note',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        to='focus.Note'),
        ),
        migrations.AddField(
                model_name='note',
                name='user',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
                model_name='comment',
                name='note',
                field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Note'),
        ),
    ]
