# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('focus', '0003_auto_20161211_1751'),
    ]

    operations = [
        migrations.AlterField(
                model_name='newuser',
                name='avatar',
                field=models.ImageField(upload_to='avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
                model_name='newuser',
                name='profile',
                field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profile'),
        ),
    ]
