# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_auto_20171124_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='who comment'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Comment'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Note'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='praises', to=settings.AUTH_USER_MODEL, verbose_name='who praise'),
        ),
        migrations.AlterField(
            model_name='share',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tread',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Comment'),
        ),
        migrations.AlterField(
            model_name='tread',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Note'),
        ),
        migrations.AlterField(
            model_name='tread',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treads', to=settings.AUTH_USER_MODEL, verbose_name='who tread'),
        ),
    ]
