# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('focus', '0004_auto_20161211_1807'),
    ]

    operations = [
        migrations.AlterField(
                model_name='note',
                name='category',
                field=models.CharField(
                    choices=[('Video', 'Video'), ('Picture', 'Picture'), ('Jape', 'Jape'), ('Others', 'Others')],
                    default='Video', max_length=20, verbose_name='Belong to'),
        ),
    ]
