# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_auto_20171124_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Note'),
        ),
        migrations.AlterField(
            model_name='share',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL, verbose_name='who share'),
        ),
    ]
