# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0005_auto_20171124_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tread',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Comment'),
        ),
        migrations.AlterField(
            model_name='tread',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.Note'),
        ),
    ]
