# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0008_auto_20171124_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile',
            field=models.CharField(blank=True, max_length=255, verbose_name='profile'),
        ),
    ]
