# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0010_auto_20171124_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='share_num',
            field=models.IntegerField(default=0),
        ),
    ]
