# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('focus', '0011_auto_20161210_1519'),
    ]

    operations = [
        migrations.AddField(
                model_name='newuser',
                name='avatar',
                field=models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
                model_name='note',
                name='image',
                field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
