# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0011_auto_20171124_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
