# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0013_auto_20171124_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=75),
        ),
    ]
