# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0014_auto_20171124_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='haha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='recmd',
            field=models.IntegerField(default=0),
        ),
    ]
