# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0015_auto_20171126_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='recommend',
        ),
    ]
