# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0016_remove_note_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_set', to=settings.AUTH_USER_MODEL, verbose_name='who public'),
        ),
    ]
